--- 
abstract: write code like a tyrolean says it
author: 
  - Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0.70
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-Tiroler
no_index: 
  directory: 
    - inc
    - t
requires: 
  Filter::Simple: 0
  perl: 5.6.0
version: 0.05
